apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-static-web
  labels:
    version: "1.2"
    date: "2023-07"
spec:
  selector:
    matchLabels:
      app: static-web
      server: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: static-web
        server: nginx
    spec:
      containers:
      - name: nginx-static-web
        image: abhyuni/nginx:1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret
