apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
stringData:
  password: mypassword
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config2
type: Opaque
stringData:
  conf: |
    여기에도 볼륨으로 마운트하여
    사용하는 경우 여러 줄의 문자
    열 값을 입력하여 사용할 수
    있습니다.
# data:
#   password: bXlwYXNzd29yZAo=
