apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    env:
    - name: ENV_NAME
      value: "env value"
    - name: KEY
      valueFrom:
        configMapKeyRef:
          name: config1
          key: key
    - name: VERSION
      valueFrom:
        configMapKeyRef:
          name: config1
          key: version
    envFrom:
    - configMapRef:
        name: config1
    volumeMounts:
    - name: config-volume
      mountPath: /config
      readOnly: true
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: config1
  - name: nginx-config-volume
    configMap:
      name: nginx-default-conf
  imagePullSecrets:
  - name: docker-pull-secret
