apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-read-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
