apiVersion: v1
kind: Pod
metadata:
  name: nginx-ssl-tls-pod
  labels:
    name: nginx-ssl-tls-pod
spec:
  containers:
  - name: nginx-ssl-tls-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 443
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/
      readOnly: true
    - name: nginx-ssl-tls
      mountPath: /etc/nginx/ssl/
      readOnly: true
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config-map
  - name: nginx-ssl-tls
    secret:
      secretName: nginx-ssl-tls-secret
  imagePullSecrets:
  - name: docker-pull-secret
