# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "mz-server"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "docker-server"
      vb.cpus = 4
      vb.memory = 8192
    end
    ubuntu.vm.network "forwarded_port", guest: 8080, host: 80, host_ip: "127.0.0.1"
    ubuntu.vm.network "forwarded_port", guest: 8081, host: 80, host_ip: "127.0.0.2"
    ubuntu.vm.network "private_network", ip: "192.168.33.10"
    ubuntu.vm.provision "shell", inline: <<-SCRIPT
      sudo apt-get update -y
      sudo apt-get install -y ca-certificates curl gnupg
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg
      echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update -y
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      sudo usermod -a -G docker vagrant
      docker login -u abhyuni --password-stdin < /vagrant/env/docker_token
      docker volume create --label service=web --label creater=hyun web_src_vol
      sudo cp -r /vagrant/htdocs/* /var/lib/docker/volumes/web_src_vol/_data/
      docker run -d -p 8080:80 -v web_src_vol:/usr/local/apache2/htdocs --name web-server1 httpd
      docker run -d -p 8081:80 -v web_src_vol:/usr/share/nginx/html --name web-server2 nginx
    SCRIPT
  end
end
