apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-rolebinding
  namespace: default
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1-role
