apiVersion: v1
kind: Namespace
metadata:
  name: other
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: other-role
  namespace: other
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: other-rolebinding
  namespace: other
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: user1
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: other-role
